[env:nodemcuv2]
lib_deps =
    knolleary/PubSubClient@^2.8
upload_protocol = espota
upload_port = soil-monitor.local
upload_flags =
    --port=8266
platform = espressif8266
board = nodemcuv2
framework = arduino
