[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7
build_flags =
    -DMQTT_MAX_PACKET_SIZE=512
monitor_speed = 115200
upload_protocol = espota
upload_port = soil-monitor.local
upload_flags =
    --port=8266